### PR TITLE
Support latest libvterm

### PR DESCRIPTION
**Pull request by mattn**
Now go-libvterm support new build constraints "libvterm"

@micromaomao You can bulid latest libvterm with `libvterm` build-constraints. I copied code from your PR https://github.com/mattn/go-libvterm/pull/2 . Thanks. How do you think about this?

### CODE REVIEW

**Comment by micromaomao** [comment]
This is OK. However, if you are doing it this way, which requires a manual `make` before using the package (if the latest libvterm is needed), the libvterm source don't necessarily need to be bundled. Most of the case (without the build tag libvterm) it would not need the bundled source code. In case the latest libvterm is needed, a command like

    bzr get http://bazaar.leonerd.org.uk/c/libvterm/

in the `Makefile` could automatically download the source when needed.

I'm just suggesting. This keeps the repo clean (the core idea is that most of the builds won't need the bundled source anyway). What do you think?

**Comment by mattn** [comment]
Now removed bundled libvterm.

**Comment by micromaomao** [comment]
These changes looks good. I don't really know what is the best way to do this kinds of things. You can merge this now I think.

**Comment by mattn** [comment]
Thanks again for your contribution.

**Pull request merged**
